config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  get 'feed'               => 'users#feed'
  get 'microposts'         => 'users#microposts'
  get 'followers'          => 'users#followers'
  get 'following'          => 'users#following'
  get 'search_users'       => 'users#search_users'
  get 'search_microposts'  => 'users#search_microposts'

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts do
    member { post :vote }
  end
  resources :relationships, only: [      :create, :destroy]
  resources :retweets,      only: [      :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  
  # バリデーション定義
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 500 }
  validates :location, length: { maximum: 100 }
  has_secure_password
  
  # リレーションシップ定義
  has_many :microposts
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower

  has_many :user_retweets,          class_name:  "Retweet",
                                    foreign_key: "user_id",
                                    dependent:   :destroy
  has_many :user_microposts, through: :user_retweets, source: :micropost

  # Active Record Reputation System
  # http://railscasts.com/episodes/364-active-record-reputation-system?language=ja&view=asciicast
  has_reputation :likes, source: {reputation: :likes, of: :microposts}, aggregated_by: :sum
  has_many :evaluations, class_name: "ReputationSystem::Evaluation", as: :source

  # モデルメソッド定義
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    cond1 = Micropost.where('retweets.user_id' => following_user_ids)
    cond2 = Micropost.where('microposts.user_id' => following_user_ids)
    
    cond1 = cond1.where_values.reduce(:and)
    cond2 = cond2.where_values.reduce(:and)
    
    Micropost.joins("LEFT JOIN retweets ON microposts.id = retweets.micropost_id").where(cond1.or(cond2)).uniq
  end

  # リツイート関係のメソッド
  # あるmicropostをリツイートする
  def retweet(micropost)
    user_retweets.create(micropost_id: micropost.id)
  end

  # フォローしているユーザーをアンフォローする
  def unretweet(micropost)
    user_retweets.find_by(micropost_id: micropost.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def retweet?(micropost)
    user_microposts.include?(micropost)
  end
  
  # あるマイクロポストにイイネしたかどうか
  def liked_for?(micropost)
    evaluations.where(target_type: micropost.class, target_id: micropost.id).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :microposts, :feed, :update, :destroy]
  
  def index
    if !logged_in?
      redirect_to root_url
    end

    search_users
    @micropost = current_user.microposts.build
  end

  def search_users
    @users = search_user
  end
  
  def search_microposts
    @microposts = search_micropost
  end

  def show
    if logged_in?
      set_user
      @micropost = @user.microposts.build
      feed
    else
      redirect_to root_url
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] =  I18n.t('users_create.log_in_as.pre') + @user.name + I18n.t('users_create.log_in_as.suf')
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = set_user
    if current_user != @user
      flash.now[:danger] = '不正なページ遷移を検出しました'
      redirect_to root_url
    end
  end

  # users_controller.rb
  def update
    if !check_old_pwd
      flash.now[:danger] = 'パスワードが一致しません'
      return render 'edit'
    end
    
    profile = user_profile
    profile.delete(:old_password)

    if @user.update(profile)
      # 保存に成功した場合はトップページへリダイレクト
      flash.now[:info] = 'メッセージを編集しました'
      redirect_to @user
    else
      # 保存に失敗した場合は編集画面へ戻す
      flash.now[:danger] = 'この内容は登録できません'
      render 'edit'
    end
  end

  def following
    @following = User.find(params[:follower_id]).following_users.order(:created_at).reverse_order
  end
  
  def followers
    @followers = User.find(params[:followed_id]).follower_users.order(:created_at).reverse_order
  end
  
  def microposts
    @microposts = @user.microposts.order(:created_at).reverse_order
  end
  
  def feed
    @microposts = @user.feed_items.includes(:user).order(:created_at).reverse_order
  end
    

private

  # get parameters for sinup
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
    
  # get parameters for profile editing
  def user_profile
    params.require(:user).permit(:name, :email, :description, :location, :password, :password_confirmation, :old_password)
  end
  
  # get parameters for search
  def search_params
    params.permit(:q, :page)
  end
  
  def check_old_pwd
    if u = params[:user]
      old_pwd = u[:old_password]
      new_pwd = u[:password]
      confirm = u[:password_confirmation]
      return true if old_pwd.blank? && new_pwd.blank? && confirm.blank?
      return false unless old_pwd.presence && new_pwd.presence && confirm.presence
      !!@user.authenticate(old_pwd) 
    else
      false # 通常はここには来ないけど安全策
    end
  end
 
  def set_user
    @user=User.find(params[:id])
  end
  
  def set_keyword_array
  end

  def search_user
    return users = clear_search_condition if params[:q].blank?

    q = search_params[:q]
    session[:q] = q
    keyword_arrays = q.gsub(/　/," ").split()

    # 以下、モデルのクラスメソッドにしたい。
    # 理想は、User.find_by_array(column_name, keyword_arrays)とかにしたい。
    # でもって、Micropostの方と共通化したい。
    users = User.arel_table[:name]
    users_sel = users.matches("\%#{keyword_arrays[0]}\%")
    for i in 1...keyword_arrays.length
      users_sel = users_sel.or(users.matches("\%#{keyword_arrays[i]}\%"))
    end

    User.where(users_sel).order(:created_at).reverse_order
  end

  def search_micropost
    return microposts = clear_search_condition if params[:q].blank?
    
    q = search_params[:q]
    session[:q] = q
    keyword_arrays = q.gsub(/　/," ").split()

    # 以下、モデルのクラスメソッドにしたい。
    # 理想は、Micropost.find_by_array(column_name, keyword_arrays)とかにしたい。
    # でもって、Userの方と共通化したい。
    microposts = Micropost.arel_table[:content]
    microposts_sel = microposts.matches("\%#{keyword_arrays[0]}\%")
    for i in 1...keyword_arrays.length
      microposts_sel = microposts_sel.or(microposts.matches("\%#{keyword_arrays[i]}\%"))
    end

    Micropost.where(microposts_sel).order(:created_at).reverse_order
  end

  def clear_search_condition
    session[:q] = ""
    Array.new()
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_feed_list.html.erb
<% if @microposts.present? %>
  <%= render 'shared/micropost_list' %>
<% else %>
  <h4>
    <%= I18n.t('users.micropost_list.feed.no_item') %>
  </h4>
<% end %>

app/views/users/_follow.html.erb
<%= link_to relationships_path(followed_id: user.id), method: "post", remote: true do %>
  <span class="label label-info glyphicon glyphicon-heart">
    <%= I18n.t('users.follow.follow') %>
  </span>
<% end %>

app/views/users/_follower_list.html.erb
<h3>
  Followers(<%= @user.follower_users.count %>)
</h3>

<ol class="followers">
  <% @user.follower_users.each do |u| %>
    <li id="follows-<%= u.id %>">
      <%= link_to gravatar_for(u, size: 50), u %>
      <span class="user"><%= link_to u.name, u %></span>
      <span class="content"><%= link_to u.description, u %></span>
      <span class="timestamp"><%= link_to u.location, u %></span>
    </li>
  <% end %>
</ol>

app/views/users/_followers_list.html.erb
<% if @followers.present? %>
  <ol class="followers">
    <% @followers.reverse_each do |u| %>
      <%= render partial: 'users/followuser', locals: { u: u } %>
    <% end %>
  </ol>
<% else %>
  <h4>
    <%= I18n.t('users.micropost_list.followers.no_item') %>
  </h4>
<% end %>

app/views/users/_following_list.html.erb
<% if @following.present? %>
  <ol class="following">
    <% @following.reverse_each do |u| %>
      <%= render partial: 'users/followuser', locals: { u: u } %>
    <% end %>
  </ol>
<% else %>
  <h4>
    <%= I18n.t('users.micropost_list.following.no_item') %>
  </h4>
<% end %>

app/views/users/_followuser.html.erb
<li id="follows-<%= u.id %>">
  <%= link_to gravatar_for(u, size: 50), u %>
  <span class="user">
    <%= link_to u.name, u %><br>
    <%= render 'shared/follow_form', user: u %>
  </span>
  <span class="content"><%= u.description %> &nbsp;</span>
  <span class="location"><%= u.location %> &nbsp;</span>
</li>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %> 
  
  <h2 class="page-header">
    User Profile
  </h2>
    
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :description %>
  <%= f.text_area :description, placeholder:"自己紹介 (MAX 500文字)" %>
  
  <%= f.label :location %>
  <%= f.text_area :location, placeholder:"場所 (MAX 100文字)" %>

  <h2 class="page-header">
    Password
  </h2>
  
  <%= f.label :old_password %>
  <%= f.password_field :old_password %>

  <%= f.label :password%>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation, "Verify password" %>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit "Update", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_search_result_micropost.html.erb
<% if @microposts.present? %>
  <%= render 'shared/micropost_list' %>
<% else %>
  <h4>
    <%= I18n.t('users.index.microposts.no_item') %>
  </h4>
<% end %>

app/views/users/edit.html.erb
<div class="col-lg-offset-3 col-lg-6">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>

  <%= render 'form' %>
</div>
<script>
  $(".nav_menu").removeClass("active");
  $("#settings").removeClass("hidden").addClass("active"); 
</script>

app/views/users/feed.js.erb
$("#follow_list").html("<%= escape_javascript(render('users/feed_list')) %>");
$(".tabmenu").removeClass("active");
$("#feed").addClass("active");

app/views/users/followers.js.erb
$("#follow_list").html("<%= escape_javascript(render('users/followers_list')) %>");
$(".tabmenu").removeClass("active");
$("#followers").addClass("active");

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="col-md-8">
    <ul class="nav nav-tabs nav-justified">
    	<li role="presentation" class="tabmenu active" id="users">
    	   <%= link_to I18n.t('users.index.users.tab_name'), search_users_path(:q=>session[:q]), remote: true %> 
    	</li>
    	<li role="presentation" class="tabmenu" id="microposts">
    	   <%= link_to I18n.t('users.index.microposts.tab_name'), search_microposts_path(:q=>session[:q]), remote: true %> 
    	</li>
    </ul>

    <div id="search-result">
      <%= render 'search_result_user' %>
    </div>
  </div>
</div>
<script>
  $(".nav_menu").removeClass("active");
  $("#search").removeClass("hidden").addClass("active"); 
</script>

app/views/users/search_microposts.js.erb
$("#search-result").html("<%= escape_javascript(render('users/search_result_micropost')) %>");
$(".tabmenu").removeClass("active");
$("#microposts").addClass("active");

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="col-md-8">
    <ul class="nav nav-tabs nav-justified">
    	<li role="presentation" class="tabmenu active" id="feed">
    	  <%= link_to I18n.t('users.micropost_list.feed.tab_name'), feed_path(:id=>@user.id), remote: true %>
    	</li>
    	<li role="presentation" class="tabmenu" id="microposts">
    	  <%= link_to I18n.t('users.micropost_list.micropost.tab_name'), microposts_path(:id=>@user.id), remote: true %>
    	</li>
    	<li role="presentation" class="tabmenu" id="following">
    	  <%= link_to I18n.t('users.micropost_list.following.tab_name'), following_path(:follower_id=>@user.id), remote: true %>
      </li>
    	<li role="presentation" class="tabmenu" id="followers">
    	  <%= link_to I18n.t('users.micropost_list.followers.tab_name'), followers_path(:followed_id=>@user.id), remote: true %>
      </li>
    </ul>
    <div id="follow_list">
      <%= render 'feed_list' %>
    </div>
  </div>
</div>

<script>
  $(".nav_menu").removeClass("active");
  <% if current_user == @user %>
    $("#my_page").addClass("active"); 
  <% else %>
    $("#other_page").removeClass("hidden").addClass("active"); 
  <% end %>
</script>