config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  get 'feed'               => 'users#feed'
  get 'microposts'         => 'users#microposts'
  get 'followers'          => 'users#followers'
  get 'following'          => 'users#following'
  get 'search_users'       => 'users#search_users'
  get 'search_microposts'  => 'users#search_microposts'

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts do
    member { post :vote }
  end
  resources :relationships, only: [      :create, :destroy]
  resources :retweets,      only: [      :create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <!--メッセージをふわっと表示して自然に消すjsメソッド-->
  <!--http://alfredobarron.github.io/smoke/#/-->
  <script>
    $.smkAlert({text:'<%= message %>', type:'<%= message_type %>'});
  </script>
<% end %>

app/views/shared/_follow_form.html.erb
<% if current_user != user %>
  <span class="follow_form_<%= user.id %>">
    <% if current_user.following?(user) %>
      <%= render 'users/unfollow', user: user %>
    <% else %>
      <%= render 'users/follow', user: user %>
    <% end %>
  </span>
<% end %>

app/views/shared/_genki.html.erb
<span>
  <%= micropost.reputation_for(:likes).to_i %>
  <%= I18n.t('users.micropost_list.genki') %>
</span>
&nbsp;

app/views/shared/_genki_sum.html.erb
<span class="goku">
  <span class="genkidama"></span>
</span>
<span id="genki-counter">
  <%= I18n.t('genki_sum.genki_dama_size') %>
  <%= number_with_delimiter (ReputationSystem::Evaluation.sum(:value).to_i + 1000) %> / <%= number_with_delimiter 18000 %>
</span>
<span id="enemy"></span>

<!-- デバッグ用 -->
<% ratio = 1 %>
<script>
  $(".genkidama")
  .height(<%= ReputationSystem::Evaluation.sum(:value).to_i * ratio / 60 + 20 %>)
  .width(<%=  ReputationSystem::Evaluation.sum(:value).to_i * ratio / 60 + 20 %>)
  .css("top",<%= ReputationSystem::Evaluation.sum(:value).to_i * ratio  / 30 * -0.5 + 7 %>)
  .css("left",<%= ReputationSystem::Evaluation.sum(:value).to_i * ratio / 60 * -0.5 + 28 %>)
  ;
</script>

<span class="energy">
  <span class="hidden"></span>
</span>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%#= render 'shared/error_messages', object: f %>
  <div class="field">
    <%= f.text_area :content, placeholder: I18n.t('users.side_bar.whats_happening') %>
  </div>
  <%= f.submit I18n.t('users.side_bar.submit'), class: "btn btn-primary" %>
<% end %>

app/views/shared/_micropost_list.html.erb
<ol class="microposts">
  <% @microposts.each do |micropost| %>
    <% @m = micropost %>
    <%= render partial: 'microposts/micropost', locals: { micropost: micropost } %>
  <% end %>
</ol>

app/views/shared/_retweet.html.erb
<%= link_to retweets_path(:micropost_id=>@m.id), method: :post, remote: true do %>
  <span class="label label-info glyphicon glyphicon-retweet" > <%= I18n.t('users.micropost_list.retweet') %></span> 
<% end %>

app/views/shared/_retweet_form.html.erb
<span id="genki-<%= micropost.id %>">
  <%= render 'shared/genki', micropost: micropost %>
</span>
<% if current_user.id != @m.user_id %>
  <span id="retweet_form-<%= @m.id %>">
    <% if current_user.retweet?(@m) %>
      <%= render 'shared/unretweet' %>
    <% else %>
      <%= render 'shared/retweet' %>
    <% end %>
  </span>
  <span id="vote-form-<%= micropost.id %>">
    <%= render 'shared/vote_form', micropost: micropost %>
  </span>
<% else %>
  <%= link_to micropost, method: :delete, data: { confirm: I18n.t('users.micropost_list.you_sure') } do %>
    <span class="label label-danger glyphicon glyphicon-trash"> <%= I18n.t("users.micropost_list.delete") %></span>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<% if @user.present? %>
  <% disp_user = @user %>
<% else %>
  <% disp_user = current_user %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="media">
      <a class="media-left" href="#">
        <%= gravatar_for disp_user %>
      </a>
      <div class="media-body">
        <h3 class="media-heading">
          <%= disp_user.name %>
        </h3>
        <span>
          <%= pluralize(disp_user.microposts.count, I18n.t('users.side_bar.micropost')) %>,
          <%= disp_user.reputation_for(:likes).to_i %> <%= I18n.t('users.side_bar.genki') %>
        </span><br>
        <%= render 'shared/follow_form', user: disp_user if current_user != disp_user%>
        <% if current_user == disp_user %>
          <h4 class="media-heading">
            <%= link_to "/users/#{current_user.id}/edit" do %>
              <span class="label label-info glyphicon glyphicon-pencil"><%= I18n.t("users.side_bar.settings") %></span>
            <% end %>
          </h4>
        <% end %>
      </div>
    </div>
    <ul class="nav nav-pills nav-stacked">
      <% if current_user == disp_user %>
        <li class="sidebar-content"><a><i class="glyphicon glyphicon-envelope"></i> <%= disp_user.email %></a></li>
      <% end %>
      <li class="sidebar-content"><a><i class="glyphicon glyphicon-user"></i> <%= disp_user.description %></a></li>
      <li class="sidebar-content"><a><i class="glyphicon glyphicon-map-marker"></i> <%= disp_user.location %></a></li>
    </ul> 
  </div>
</div>
<% if current_user == disp_user %>
  <aside>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
<% end %>

app/views/shared/_unretweet.html.erb
<%= link_to current_user.user_retweets.find_by(micropost_id: @m.id), method: :delete, remote: true do %>
  <span class="label label-success" ><%= I18n.t('users.micropost_list.unretweet') %></span> 
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/shared/_vote_form.html.erb
<% if current_user.liked_for?(micropost) %>
  <%= link_to vote_micropost_path(micropost, type: "down"), method: "post", remote: true do %>
    <span class="label label-success"> <%= I18n.t('users.micropost_list.cancel') %> </span>
  <% end %>
<% else %>
  <%= link_to vote_micropost_path(micropost, type: "up"), method: "post", remote: true do %>
    <span class="label label-info glyphicon glyphicon-thumbs-up"> <%= I18n.t('users.micropost_list.genki') %> </span>
  <% end %>
<% end %>