config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  get 'feed'               => 'users#feed'
  get 'microposts'         => 'users#microposts'
  get 'followers'          => 'users#followers'
  get 'following'          => 'users#following'
  get 'search_users'       => 'users#search_users'
  get 'search_microposts'  => 'users#search_microposts'

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts do
    member { post :vote }
  end
  resources :relationships, only: [      :create, :destroy]
  resources :retweets,      only: [      :create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav id="navigation_header">
      <ul class="nav navbar-nav navbar-left">
        <li id="home" class="nav_menu"><%= link_to I18n.t('layouts.home'), root_path %></li>
        <% if logged_in? %>
          <li id="my_page" class="nav_menu"><%= link_to I18n.t('layouts.my_page'), current_user %></li>
          <li class="dropdown nav_menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= I18n.t('layouts.account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to I18n.t('layouts.settings'), edit_user_path(current_user) if logged_in?%></li>
              <li class="divider"></li>
              <li>
                <%= link_to I18n.t('layouts.log_out'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <li id="settings" class="nav_menu hidden"><%= link_to I18n.t('layouts.settings'), '#' %></li>
          <li id="search" class="nav_menu hidden"><%= link_to I18n.t('layouts.search'), '#' %></li>
          <% @user.present? ? user_name = @user.name : user_name = "" %>
          <li id="other_page" class="nav_menu hidden"><a href="#"><%= user_name + I18n.t('layouts.other_page') %></a></li>
        <% else %>
          <li id="log_in" class="header_nav"><%= link_to I18n.t('layouts.log_in'), login_path %></li>
          <li id="sign_up" class="nav_menu hidden"><%= link_to I18n.t('layouts.sign_up'), '#' %></li>
        <% end %>
      </ul>
    </nav>
    <% if logged_in? %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-left" role="search" action="/users/">
    				<div class="form-group">
    					<input type="text" class="form-control" name="q" placeholder=<%= I18n.t('search.user_or_microposts') %>>
    				</div>
    				<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
    			</form>
    		</ul>
      </nav>
    <% end %>
  </div>
</header>
<h1 id="genki_sum">
  <%= render 'shared/genki_sum' %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <!--メッセージをふわっと表示して自然に消すjsメソッド-->
        <!--http://alfredobarron.github.io/smoke/#/-->
        <script>
          $.smkAlert({text:'<%= message %>', type:'<%= message_type %>'});
        </script>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>